### ISSUE TITLE
[Feature/Bug] Improve matches to pre-release versions

### ISSUE THREAD

**Issue by rtritto** [mskelton/yarn-plugin-outdated#35]
Match of pre-release versions (e.g. canary, alpha, beta, rc) should be like this [logic](https://semver.org/#spec-item-11).

Example:
> 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0

# Steps to reproduce
1. `yarn init -y`
2. `yarn set version berry`
3. `yarn plugin import https://github.com/mskelton/yarn-plugin-outdated/raw/v2.1.1/bundles/@yarnpkg/plugin-outdated.js`
4. `yarn add next@canary video.js@next`
5. `yarn outdated`

# Results
## Actual
yarn log:
```
➤ YN0000: ┌ Checking for outdated dependencies
➤ YN0000: └ Completed

➤ YN0000: Package    Current            Latest   Package Type
➤ YN0000: next       11.1.3-canary.29   11.1.2   dependencies
➤ YN0000: video.js   7.15.5             7.15.4   dependencies

➤ YN0000: 2 dependencies are out of date
➤ YN0000: Done with warnings
```

## Expect
No yarn log.

---
Maybe this regex can help:
```js
const regex = /^([0-9]+\.)([0-9]+\.)([0-9]+).+(\.[0-9]+)$/

console.log(value.match(regex))

// "5.0.0-rc.1" => ["5.0.0-rc.1", "5.", "0.", "0", ".1"]
// "11.1.3-canary.29" => ["11.1.3-canary.29", "11.", "1.", "3", ".29"] 
```
Or to compare use a lib like [semver](https://www.npmjs.com/package/semver).

**Comment by mskelton** [comment]
@rtritto I've opened a PR which I believe strikes a good balance with handling of pre-releases.  If the latest version is a pre-release (like in the case of `@yarnpkg` deps), it will compare the current and latest directly.  Otherwise, it will coerce any pre-release versions in your workspaces against the latest version.  For example if you have `video.js@1.0.0-alpha.1` and the latest is `video.js@1.0.1` it will be outdated but if the latest is `video.js@1.0.0` it will not be marked as outdated.

Thoughts?

**Comment by rtritto** [comment]
Logic should be to compare always latest tag with next/canary tag (or maybe all tag different from latest tag) to get newest version. Then compare it with current version to find if it's outdated.

**Comment by mskelton** [comment]
I'm not sure what you mean when you say compare always latest tag with next/canary tag.  Could you provide some examples of what you mean?

**Comment by rtritto** [comment]
1. Get *newest* version by tag versions
2. Compare *current* version with *newest* one:
    -  current >= newest? Yes, updated | No, outdated
    OR
    -  current < newest? Yes, outdated | No, updated

Examples:
1. Current version: 1.0.0
Tag=version: next=1.0.1 | latest=1.0.2 | rc=1.0.3-rc.1 | beta=1.0.2-beta.1
Newest Tag=version: rc=1.0.3-rc.1
Current version < Newest version: 1.0.0 < 1.0.3-rc.1? outdated

2. Current version: 1.0.3-rc.1
Tag=version: next=1.0.1 | latest=1.0.2 | rc=1.0.3-rc.1 | beta=1.0.2-beta.1
Newest Tag=version: rc=1.0.3-rc.1
Current version < Newest version: 1.0.3-rc.1 < 1.0.3-rc.1? updated

**Comment by mskelton** [comment]
So, the problem with example 1 is that 1.0.3-rc.1 is not marked as the latest version and rightfully so, it isn't released yet.  Thus, this plugin will mark the version as outdated with the latest version as 1.0.2.  That behavior I do not intend to change as it would result in it flagging many deps as outdated because there are alpha or rc versions when the stable latest version is installed.

The second example will be support with my change in #36 as it will not mark deps that are newer than the `latest` tag as outdated.

**Comment by rtritto** [comment]
3. Current version: 1.0.2
Tag=version: next=1.0.1 | latest=1.0.2 | rc=1.0.3-rc.1 | beta=1.0.2-beta.1
Newest Tag=version: rc=1.0.3-rc.1
Current version < Newest version: 1.0.2 < 1.0.3-rc.1

So result of this example should be updated instead of outdated.

You can add (feature) a command option to choose the newest version behavior:
- *latest* tag (default)
or
- *all* tags

**Comment by mskelton** [comment]
Your example 3 you just posted would indeed be marked as updated.  Given that I see this as a fringe case that I don't think really fits well for this plugin, I'm not going to adding this feature.
