### ISSUE TITLE
Does not work with workspaces

### ISSUE THREAD

**Issue by RipTheJacker** [mskelton/yarn-plugin-outdated#8]
It seems to only operate on the package.json in the current directory. The previous merged all them listed in the workspaces property.

**Comment by mskelton** [comment]
Hi @RipTheJacker.  That changing behavior is actually by design.  One of the pain points I had with the old version was that it was very difficult to use on just a single workspace.  That is why I made hit the default in this plugin.

That said there is a `--all` flag that you can use if you want to find outdated dependencies in all workspaces.  The `--all` flag works identically to the Yarn 1 command.

**Comment by RipTheJacker** [comment]
Ahh ok, sorry I didn't notice the flag.
